### ISSUE TITLE
Problem with adding weapons in weapon slots

### ISSUE THREAD

**Issue by Dave2211** [DigitalPagan/Mythras-Roll20-Sheet#61]
Cant add weapons to new character sheets no add modify button under weapons. Cheers

**Comment by DigitalPagan** [comment]
Hi,

Have you looked in the equipment section?  With v2 I placed weapons in the Equipment tab as it seemed to make more sense there, but I wanted to get them front and center for combat so I have a summary of them there.  You can only add/remove weapons in the equipment section however(it's also the only place with the weapons ENC value).

**Comment by DigitalPagan** [comment]
> Cant add weapons to new character sheets no add modify button under weapons. Cheers

Hi,

Have you looked in the equipment section? With v2 I placed weapons in the Equipment tab as it seemed to make more sense there, but I wanted to get them front and center for combat so I have a summary of them there. You can only add/remove weapons in the equipment section however(it's also the only place with the weapons ENC value).

**Comment by DigitalPagan** [comment]
In v3.0 there is only one weapon section to help avoid this issue.  It not longer needs to be front and center cause the favored weapons will be listed in the cs rolls.
