### ISSUE TITLE
Rolling for Hit location error when passive blocks set

### ISSUE THREAD

**Issue by CJEB** [DigitalPagan/Mythras-Roll20-Sheet#64]
If passive block check boxes are ticked this error comes up when rolling for location
SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but "o" found.

**Comment by DigitalPagan** [comment]
This was corrected in v3.0
