### ISSUE TITLE
Error when toggling Passive Blocking on Compact Tab

### ISSUE THREAD

**Issue by WillDigForFood** [DigitalPagan/Mythras-Roll20-Sheet#66]
Using the 'Compact' tab of the Character Sheet to select hit locations to Passively Block results in a Syntax Error being thrown when attempting to use the sheet's hit location macro:

SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but "o" found.

Using the 'Core' tab to select hit locations to Passively Block works fine, and will report the correct results when using the hit location macro on either the Compact or Core tab.

Other oddity I've noticed is that if you select a hit location to passively block on the Core tab, then swap over to the Compact tab and select the same location there, it will de-select the location to be passively blocked on the Core tab (and, of course, throw an error if you try to use the hit location macro.) The inverse is not true (i.e., using the Compact tab to select a location that is not selected on the Core tab will not automatically select it on the core tab.)

**Comment by DigitalPagan** [comment]
Hi and thanks for reporting.  I'm currently working on the next version of the sheet which is a complete re-write so hopefully this doesn't get pulled into the next version but I'll do some explicit testing to ensure it doesn't.

**Comment by DigitalPagan** [comment]
No more compact sheet in v3.0 so this issue in no longer relavent.
